// Code generated by "stringer -type=SessionState,SessionType"; DO NOT EDIT.

package smpp

import "strconv"

const _SessionState_name = "StateOpenStateBindingStateBoundTxStateBoundRxStateBoundTRxStateUnbindingStateClosingStateClosed"

var _SessionState_index = [...]uint8{0, 9, 21, 33, 45, 58, 72, 84, 95}

func (i SessionState) String() string {
	if i < 0 || i >= SessionState(len(_SessionState_index)-1) {
		return "SessionState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SessionState_name[_SessionState_index[i]:_SessionState_index[i+1]]
}

const _SessionType_name = "ESMESMSC"

var _SessionType_index = [...]uint8{0, 4, 8}

func (i SessionType) String() string {
	if i < 0 || i >= SessionType(len(_SessionType_index)-1) {
		return "SessionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SessionType_name[_SessionType_index[i]:_SessionType_index[i+1]]
}
