// Code generated by "stringer -type=Status,CommandID,TagID"; DO NOT EDIT.

package pdu

import "strconv"

const _Status_name = "StatusOKStatusInvMsgLenStatusInvCmdLenStatusInvCmdIDStatusInvBndStatusAlyBndStatusInvPrtFlgStatusInvRegDlvFlgStatusSysErrStatusInvSrcAdrStatusInvDstAdrStatusInvMsgIDStatusBindFailStatusInvPaswdStatusInvSysIDStatusCancelFailStatusReplaceFailStatusMsgQFulStatusInvSerTypStatusInvNumDeStatusInvDLNameStatusInvDestFlagStatusInvSubRepStatusInvEsmClassStatusCntSubDLStatusSubmitFailStatusInvSrcTONStatusInvSrcNPIStatusInvDstTONStatusInvDstNPIStatusInvSysTypStatusInvRepFlagStatusInvNumMsgsStatusThrottledStatusInvSchedStatusInvExpiryStatusInvDftMsgIDStatusTempAppErrStatusPermAppErrStatusRejeAppErrStatusQueryFailStatusInvOptParStreamStatusOptParNotAllwdStatusInvParLenStatusMissingOptParamStatusInvOptParamValStatusDeliveryFailureStatusUnknownErr"

var _Status_map = map[Status]string{
	0:   _Status_name[0:8],
	1:   _Status_name[8:23],
	2:   _Status_name[23:38],
	3:   _Status_name[38:52],
	4:   _Status_name[52:64],
	5:   _Status_name[64:76],
	6:   _Status_name[76:91],
	7:   _Status_name[91:109],
	8:   _Status_name[109:121],
	10:  _Status_name[121:136],
	11:  _Status_name[136:151],
	12:  _Status_name[151:165],
	13:  _Status_name[165:179],
	14:  _Status_name[179:193],
	15:  _Status_name[193:207],
	17:  _Status_name[207:223],
	19:  _Status_name[223:240],
	20:  _Status_name[240:253],
	21:  _Status_name[253:268],
	51:  _Status_name[268:282],
	52:  _Status_name[282:297],
	64:  _Status_name[297:314],
	66:  _Status_name[314:329],
	67:  _Status_name[329:346],
	68:  _Status_name[346:360],
	69:  _Status_name[360:376],
	72:  _Status_name[376:391],
	73:  _Status_name[391:406],
	80:  _Status_name[406:421],
	81:  _Status_name[421:436],
	83:  _Status_name[436:451],
	84:  _Status_name[451:467],
	85:  _Status_name[467:483],
	88:  _Status_name[483:498],
	97:  _Status_name[498:512],
	98:  _Status_name[512:527],
	99:  _Status_name[527:544],
	100: _Status_name[544:560],
	101: _Status_name[560:576],
	102: _Status_name[576:592],
	103: _Status_name[592:607],
	192: _Status_name[607:628],
	193: _Status_name[628:648],
	194: _Status_name[648:663],
	195: _Status_name[663:684],
	196: _Status_name[684:704],
	254: _Status_name[704:725],
	255: _Status_name[725:741],
}

func (i Status) String() string {
	if str, ok := _Status_map[i]; ok {
		return str
	}
	return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
}

const (
	_CommandID_name_0 = "BindReceiverIDBindTransmitterIDQuerySmIDSubmitSmIDDeliverSmIDUnbindIDReplaceSmIDCancelSmIDBindTransceiverID"
	_CommandID_name_1 = "OutbindID"
	_CommandID_name_2 = "EnquireLinkID"
	_CommandID_name_3 = "SubmitMultiID"
	_CommandID_name_4 = "AlertNotificationIDDataSmID"
	_CommandID_name_5 = "GenericNackIDBindReceiverRespIDBindTransmitterRespIDQuerySmRespIDSubmitSmRespIDDeliverSmRespIDUnbindRespIDReplaceSmRespIDCancelSmRespIDBindTransceiverRespID"
	_CommandID_name_6 = "EnquireLinkRespID"
	_CommandID_name_7 = "SubmitMultiRespID"
	_CommandID_name_8 = "DataSmRespID"
)

var (
	_CommandID_index_0 = [...]uint8{0, 14, 31, 40, 50, 61, 69, 80, 90, 107}
	_CommandID_index_4 = [...]uint8{0, 19, 27}
	_CommandID_index_5 = [...]uint8{0, 13, 31, 52, 65, 79, 94, 106, 121, 135, 156}
)

func (i CommandID) String() string {
	switch {
	case 1 <= i && i <= 9:
		i -= 1
		return _CommandID_name_0[_CommandID_index_0[i]:_CommandID_index_0[i+1]]
	case i == 11:
		return _CommandID_name_1
	case i == 21:
		return _CommandID_name_2
	case i == 33:
		return _CommandID_name_3
	case 258 <= i && i <= 259:
		i -= 258
		return _CommandID_name_4[_CommandID_index_4[i]:_CommandID_index_4[i+1]]
	case 2147483648 <= i && i <= 2147483657:
		i -= 2147483648
		return _CommandID_name_5[_CommandID_index_5[i]:_CommandID_index_5[i+1]]
	case i == 2147483669:
		return _CommandID_name_6
	case i == 2147483681:
		return _CommandID_name_7
	case i == 2147483907:
		return _CommandID_name_8
	default:
		return "CommandID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}

const _TagID_name = "TagDestAddrSubUnitTagDestNetworkTypeTagDestBearerTypeTagDestTelematicsIDTagSourceAddrSubunitTagSourceNetworkTypeTagSourceBearerTypeTagSourceTelematicsIDTagQosTimeToLiveTagPayloadTypeTagAdditionalStatusInfoTeTagReceiptedMessageIDTagMsMsgWaitFacilitiesTagPrivacyIndicatorTagSourceSubaddressTagDestSubaddressTagUserMessageReferenceTagUserResponseCodeTagSourcePortTagDestinationPortTagSarMsgRefNumTagLanguageIndicatorTagSarTotalSegmentsTagSarSegmentSeqnumTagScInterfaceVersionTagCallbackNumPresIndTagCallbackNumATagNumberOfMessagesTagCallbackNumTagDpfResultTagSetDPFTagMsAvailabilityStatusTagNetworkErrorCodeTagMessagePayloadTagDeliveryFailureReasonTagMoreMessagesToSendTagMessageStateTagUssdServiceOpTagDisplayTimeTagSmsSignalTagMsValidityTagAlertOnMessageDelivTagItsReplyTypeTagItsSessionInfo"

var _TagID_map = map[TagID]string{
	5:    _TagID_name[0:18],
	6:    _TagID_name[18:36],
	7:    _TagID_name[36:53],
	8:    _TagID_name[53:72],
	13:   _TagID_name[72:92],
	14:   _TagID_name[92:112],
	15:   _TagID_name[112:131],
	16:   _TagID_name[131:152],
	23:   _TagID_name[152:168],
	25:   _TagID_name[168:182],
	29:   _TagID_name[182:207],
	30:   _TagID_name[207:228],
	48:   _TagID_name[228:250],
	513:  _TagID_name[250:269],
	514:  _TagID_name[269:288],
	515:  _TagID_name[288:305],
	516:  _TagID_name[305:328],
	517:  _TagID_name[328:347],
	522:  _TagID_name[347:360],
	523:  _TagID_name[360:378],
	524:  _TagID_name[378:393],
	525:  _TagID_name[393:413],
	526:  _TagID_name[413:432],
	527:  _TagID_name[432:451],
	528:  _TagID_name[451:472],
	770:  _TagID_name[472:493],
	771:  _TagID_name[493:508],
	772:  _TagID_name[508:527],
	897:  _TagID_name[527:541],
	1056: _TagID_name[541:553],
	1057: _TagID_name[553:562],
	1058: _TagID_name[562:585],
	1059: _TagID_name[585:604],
	1060: _TagID_name[604:621],
	1061: _TagID_name[621:645],
	1062: _TagID_name[645:666],
	1063: _TagID_name[666:681],
	1281: _TagID_name[681:697],
	4609: _TagID_name[697:711],
	4611: _TagID_name[711:723],
	4612: _TagID_name[723:736],
	4876: _TagID_name[736:758],
	4992: _TagID_name[758:773],
	4995: _TagID_name[773:790],
}

func (i TagID) String() string {
	if str, ok := _TagID_map[i]; ok {
		return str
	}
	return "TagID(" + strconv.FormatInt(int64(i), 10) + ")"
}
